### ISSUE TITLE
Self-closing elements such cause Left Expected EOF if there is whitespace before the closing slash.

### ISSUE THREAD

**Issue by kindaro** [carymrobbins/purescript-html-parser#3]
Hello.

I've been trying the parser on some real world examples and noticed a parse error would occur if there is a space bar in a self-closed void tag with attributes.

These all work right:
```
> parseHTML "<br/>"
(Right (VoidElement "br" (Nil) : Nil))

> parseHTML "<br />"
(Right (VoidElement "br" (Nil) : Nil))

> parseHTML "<br class=\"a\"/>"
(Right (VoidElement "br" ((Attribute "class" "a" : Nil)) : Nil))
```

But this one (that has both an attribute and a white space before the closing slash) gives a Left.
```
> parseHTML "<br class=\"a\" />"
(Left Expected EOF)
```

The same happens with some other void tags such as `img`.

I believe this to be an error in the parser.

**Comment by carymrobbins** [comment]
It looks like it attempts to `skipSpaces` [here](https://github.com/carymrobbins/purescript-html-parser/blob/5f7e7859a3e34bfa672dd03960b855b6cff25625/src/Text/HTML/Parser/Internal.purs#L58) before parsing the `/>`, but I guess that's not working as intended. I'd recommend adding a [test case](https://github.com/carymrobbins/purescript-html-parser/blob/5f7e7859a3e34bfa672dd03960b855b6cff25625/test/Main.purs) if you uncover the issue.

**Comment by kindaro** [comment]
I believe the reason is that it has `sepBy` where it should have`sepEndBy`.

I made a patch and a [pull request](github.com/carymrobbins/purescript-html-parser/pull/4).

**Comment by kindaro** [comment]
( In fact, the bug affects non-void tags as well. It only matters if there's whitespace after attributes. )
